name: 'Helen Tootsi'
tageline: 'This is the tagline of the site'


seo:
  author: 'Helen Tootsi'
  description: ''
  keywords: ''

contact:
  phone: '+1 (202) 258 2640'
  email: 'sayhi@bivee.co'

pygments: true
markdown: kramdown
paginate: 10
version: 0.9

url: ''
permalink: /:year/:title

social:
  fb: 'tootsi'
  tw: 'tootsi'
  in: 'tootsi'
  insta: 'http://www.instagram.com/htootsi'

google:
  analytics : ''
  verification : ''