name: 'Helen Tootsi'
tageline: 'This is the tagline of the site'
pygments: true
markdown: kramdown
paginate: 5
version: 0.9

seo:
  author: 'Helen Tootsi'
  description: ''
  keywords: ''

author:
  bio: ''

url: ''
permalink: /:year/:title

social:
  fb:
  tw: 'http://www.twitter.com/'
  in: 'http://uk.linkedin.com/in/'
  insta: 'http://www.instagram.com/'

google:
  analytics : ''
  verification : ''

assets:
  img: '/assets/images/'
  css: '/assets/stylesheets/'
  js: '/assets/javascripts/'  