name: 'Helen Tootsi'
tagline: 'Film, Creative, Writing'
pygments: false
markdown: kramdown
version: 0.9

headline: The world is a book and those who do not travel read only one page
subheadline:

seo:
  author: 'Helen Tootsi'

permalink: /:year/:title

social:
  tw: 'http://www.twitter.com/'
  in: 'uk.linkedin.com/in/helentootsi'
  insta: 'http://www.instagram.com/htootsi'

assets:
  img: '/assets/images/'
  css: '/assets/stylesheets/'
  js: '/assets/javascripts/'  