name: 'Helen Tootsi'
tageline: 'This is the tagline of the site'
pygments: true
markdown: kramdown
paginate: 5
version: 0.9

seo:
  author: 'Helen Tootsi'
  description: ''
  keywords: ''

author:
  bio: 'Your bio comes here'

url: ''
permalink: /:year/:title

social:
  fb: 'tootsi'
  tw: 'tootsi'
  in: 'tootsi'
  insta: 'http://www.instagram.com/htootsi'

google:
  analytics : ''
  verification : ''