name: 'Helen Tootsi'
tageline: 'This is the tagline of the site'
pygments: true
markdown: kramdown
paginate: 5
version: 0.9

seo:
  author: 'Helen Tootsi'
  description: ''
  keywords: ''

author:
  bio: 'Your bio comes here'

url: ''
permalink: /:year/:title

social:
<<<<<<< HEAD
  fb:
=======
  fb: 
>>>>>>> FETCH_HEAD
  tw: 'http://www.twitter.com/helentootsi'
  in: 'http://uk.linkedin.com/in/helentootsi'
  insta: 'http://www.instagram.com/htootsi'

google:
  analytics : ''
  verification : ''