name: 'Helen Tootsi'
tagline: 'Creative, Film Production, Writer'
pygments: false
markdown: kramdown
paginate: 5
version: 0.9

seo:
  author: 'Helen Tootsi'
  description: ''
  keywords: ''

url: ''
permalink: /:year/:title

social:
  fb:
  tw: 'http://www.twitter.com/'
  in: 'http://uk.linkedin.com/in/helentootsi'
  insta: 'http://www.instagram.com/htootsi'

google:
  analytics : ''
  verification : ''

assets:
  img: '/assets/images/'
  css: '/assets/stylesheets/'
  js: '/assets/javascripts/'  